[package]
name = "dawlib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
dawmacros = { path = "../dawmacros" }
reqwest = "0.11.14"
serde_json = "1.0"
deku = "0.16"